### ISSUE TITLE
Appreciation Issue xD

### ISSUE THREAD

**Issue by saksham1211** [jatint17/image-editing#1]
Great Job Mr. Takkar!

Keep up the good work.

**Comment by saksham1211** [comment]
HI Takkar, 

How you doing?

**Comment by saksham1211** [comment]
Lets do something big together bro, you are a great coder and problem solver, lets connect and create something big!
let me know what you think.

**Comment by jatint17** [comment]
@saksham1211 thanks for the recorgnition brother, i have an idea about a project, let's discuss

**Comment by saksham1211** [comment]
Let's connect soon!
